In [94]:
import numpy as np

In [95]:
my_list = [1,2,3,4]
arr = np.array(my_list)

In [96]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
np.arange(0, 10, 2 )# o ultimo é opcional

array([0, 2, 4, 6, 8])

In [98]:
np.zeros(3)

array([0., 0., 0.])

In [99]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [100]:
np.ones(3)

array([1., 1., 1.])

In [101]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [102]:
np.linspace(0, 5, 10) # quantos pontos igualmente espaçados entre dois numeros, (de, até, quantos)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [103]:
np.eye(4) # cria uma matriz identidade de tamanho x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [104]:
np.random.rand(5)

array([0.82181976, 0.72579121, 0.19605066, 0.43613883, 0.11390387])

In [105]:
np.random.randn(5)

array([1.08120673, 1.13220786, 1.22076171, 0.04849756, 0.59081542])

In [106]:
np.random.randn(5,5)

array([[-1.5585342 , -0.7601017 , -0.9617527 , -1.87079462, -0.86897513],
       [-0.3370286 ,  0.13732388,  1.11592944,  1.67390287, -1.26350153],
       [-0.25986719, -1.32558868, -0.88404343, -1.63247024, -0.42051071],
       [ 1.13673328, -0.10312325, -0.6265164 , -0.01547914, -1.46164508],
       [ 0.26584897,  2.98622114, -0.39445634,  1.39035145,  0.15466143]])

In [107]:
np.random.randint(1, 100, 10) # (de, até, qtd)

array([94, 24, 17, 44, 26, 51, 42, 59, 57, 89])

In [108]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [112]:
ranarr.max() # encontra maior valor

49

In [113]:
ranarr.min() #encontra menor valor

4

In [114]:
ranarr.argmax() # encontra a pos do maior valor

8

In [115]:
ranarr.argmin() # encontra a pos do menor valor

0

In [119]:
arr.shape

(25,)

In [120]:
arr = arr.reshape(5,5) # re-formata o array, por ex de um arr para uma matriz

In [121]:
arr.shape

(5, 5)

In [122]:
arr.dtype

dtype('int64')