In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr[8]

8

In [3]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
slice_of_arr = arr[0:6]
slice_of_arr[:] = 99
arr # n é uma copia, mas sim uma referencia do original

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [10]:
arr_copy = arr.copy()
arr_copy[:] = 100
print(arr_copy)
print(arr)

[100 100 100 100 100 100 100 100 100 100 100]
[99 99 99 99 99 99  6  7  8  9 10]


In [14]:
matriz = np.arange(5, 46, 5).reshape(3, 3)
matriz

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
print(matriz[0])
print(matriz[2][1])
print(matriz[2,1])
print(matriz[:2,1:])

[ 5 10 15]
40
40
[[10 15]
 [25 30]]


In [21]:
arr = np.arange(1,11)

In [26]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])