In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4]
arr = np.array(my_list)

In [4]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0, 10, 2 )# o ultimo é opcional

array([0, 2, 4, 6, 8])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.linspace(0, 5, 10) # quantos pontos igualmente espaçados entre dois numeros, (de, até, quantos)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.eye(4) # cria uma matriz identidade de tamanho x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.69603065, 0.7069436 , 0.76490764, 0.94314656, 0.00695561])

In [13]:
np.random.randn(5)

array([ 0.9479043 ,  0.21124442,  0.68911861, -0.28314623, -0.13466419])

In [14]:
np.random.randn(5,5)

array([[ 1.23924497,  0.41639576,  0.77255446,  0.20198107, -0.01982114],
       [ 0.5584927 , -3.04821187, -0.08598784, -0.43983253, -1.10131941],
       [ 0.65614521,  1.32271507, -0.2599321 ,  0.24321696, -0.02183543],
       [ 2.50369696, -0.37684385,  0.2669694 ,  1.72267726, -0.50831153],
       [ 0.53945283,  0.80923275,  0.20894563,  0.48297535,  1.85196436]])

In [15]:
np.random.randint(1, 100, 10) # (de, até, qtd)

array([85, 72, 90, 75, 79, 73, 14, 98, 89, 92])

In [16]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [17]:
ranarr.max() # encontra maior valor

46

In [18]:
ranarr.min() #encontra menor valor

2

In [19]:
ranarr.argmax() # encontra a pos do maior valor

0

In [20]:
ranarr.argmin() # encontra a pos do menor valor

9

In [21]:
arr.shape

(25,)

In [22]:
arr = arr.reshape(5,5) # re-formata o array, por ex de um arr para uma matriz

In [23]:
arr.shape

(5, 5)

In [24]:
arr.dtype

dtype('int64')